#!/bin/bash
. ./lib

options=()
options+=("gnome" "")
options+=("gnome-extra" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Gnome Minimal Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'gnome')
    require install/desktop/gnome/minimal/packages 755
    sed -i "/^package=/c\package=\"$sel\"" install/desktop/gnome/minimal/packages
    script install/desktop/gnome/minimal/packages
    svcenable gdm
  ;;
  'gnome-extra')
    require install/desktop/gnome/minimal/packages 755
    sed -i "/^package=/c\package=\"$sel\"" install/desktop/gnome/minimal/packages
    script install/desktop/gnome/minimal/packages
  ;;
esac

exit 0
