#!/bin/bash
. ./lib

options=()
options+=("Full" "")
options+=("Lite" "")
options+=("Minimal" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Gnome Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Full') menu install/desktop/gnome/full/menu;;
  'Lite') menu install/desktop/gnome/lite/menu;;
  'Minimal') menu install/desktop/gnome/minimal/menu;;
esac

exit 0
